#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=100g
#SBATCH --time=2:00:00
#SBATCH --job-name=vcf_calling
#SBATCH --mail-user=mbxsc9@nottingham.ac.uk
#SBATCH --output=/gpfs01/share/BioinfMSc/life4136_2526/rotation3/group4/Scripts/Logs/slurm-%x-%j.out
#SBATCH --error=/gpfs01/share/BioinfMSc/life4136_2526/rotation3/group4/Scripts/Logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --array=0-114   # Adjust based on number of lines in root_names.txt; first sample is "0"!

module load bcftools-uoneasy/1.18-GCC-13.2.0

mapfile -t ROOTS < /share/BioinfMSc/life4136_2526/rotation3/group4/chr_names.txt
SAMPLE=${ROOTS[$SLURM_ARRAY_TASK_ID]}

REF=/share/BioinfMSc/life4136_2526/rotation3/group4/reference_gene/Canis_lupus_familiaris.ROS_Cfam_1.0.dna.toplevel.fa
BAMLIST=/share/BioinfMSc/life4136_2526/rotation3/group4/bam_list.txt
OUT=/share/BioinfMSc/life4136_2526/rotation3/group4/vcf/dog.MQ20.${SAMPLE}.vcf.gz 

bcftools mpileup \
	-Ou \
	-f $REF \
	--min-MQ 20 \
  	--min-BQ 30 \
  	--platforms ILLUMINA \
  	--annotate FORMAT/DP,FORMAT/AD \
  	--bam-list "$BAMLIST" \
  	-r "${SAMPLE}" | \
bcftools call \
  --threads 20 \
  -m \
  -v \
  -a GQ,GP \
  -Oz \
  -o "$OUT"
bcftools index $OUT
