#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=50g
#SBATCH --time=1:00:00
#SBATCH --job-name=plink_QC
#SBATCH --output=/gpfs01/share/BioinfMSc/life4136_2526/rotation3/group4/Scripts/Logs/slurm-%x-%j.out
#SBATCH --error=/gpfs01/share/BioinfMSc/life4136_2526/rotation3/group4/Scripts/Logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxsc9@nottingham.ac.uk

source $HOME/.bash_profile
conda activate rotation3

INPUT=/share/BioinfMSc/life4136_2526/rotation3/group4/plink_data
OUTDIR=/share/BioinfMSc/life4136_2526/rotation3/group4/plink_data/plink_QC_Genotype


plink --bfile "$INPUT"/doggies_raw --allow-extra-chr --geno 0.3 --mind 0.6 --maf 0.05 --make-bed --out "$OUTDIR"/doggies_qc
